### ISSUE TITLE
app name field for 0.30 CPE should more accurately reflect the name of this client

### ISSUE THREAD

**Issue by Goodlyay** [RaphiMC/ViaLegacy#18]
https://github.com/RaphiMC/ViaLegacy/blob/5c8dda52a435553804d1e4df31bbed533a53336e/src/main/java/net/raphimc/vialegacy/protocols/classic/protocolc0_28_30toc0_28_30cpe/Protocolc0_30toc0_30cpe.java#L142

It is inappropriate to describe this as ClassiCube 1.3.5 as it is an entirely different client, with wildly varying movement and features.

**Comment by FlorianMichael** [comment]
We could add a Provider for this

**Comment by Goodlyay** [comment]
> We could add a Provider for this

What does that mean?

**Comment by RaphiMC** [comment]
Fixed in ViaLegacy 2.2.12
