### ISSUE TITLE
Why isn't ViaFabric supported?

### ISSUE THREAD

**Issue by kristibektashi** [RaphiMC/ViaLegacy#3]
https://www.curseforge.com/minecraft/mc-mods/viafabric

**Comment by RaphiMC** [comment]
ViaFabric should add support for this. I can't support every possible platform. You can use [ViaProxy](https://github.com/RaphiMC/ViaProxy) instead in the meantime

**Comment by kristibektashi** [comment]
> ViaFabric should add support for this. I can't support every possible platform. You can use [ViaProxy](https://github.com/RaphiMC/ViaProxy) instead in the meantime

I opened an issue in ViaFabric and they told me you need to fix this on your side
https://github.com/ViaVersion/ViaFabric/issues/221

**Comment by RaphiMC** [comment]
I can't fix this on my side really, because ViaFabric does not expose enough API/Hooks to load ViaLegacy

**Comment by Gaming32** [comment]
I'm working on something :)
